/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcm91_relation_ndkapp_NdkJniUtils */

#ifndef _Included_com_xcm91_relation_ndkapp_NdkJniUtils
#define _Included_com_xcm91_relation_ndkapp_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcm91_relation_ndkapp_NdkJniUtils
 * Method:    getStringFromNative
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xcm91_relation_ndkapp_NdkJniUtils_getStringFromNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
