/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndkapp_NdkJni */

#ifndef _Included_com_ndkapp_NdkJni
#define _Included_com_ndkapp_NdkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndkapp_NdkJni
 * Method:    getStringFromNative
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndkapp_NdkJni_getStringFromNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
